config/routes.rb
Railsapp::Application.routes.draw do
resources :users do
	member do
		get :following, :followers
	end
end
resources :sessions, :only => [:new, :create, :destroy]
resources :posts, :only => [:create, :destroy]
resources :relationships, :only => [:create, :destroy]
match '/signup',	:to => 'users#new'
match '/signin',	:to => 'sessions#new'
match '/signout',	:to => 'sessions#destroy'
match '/contact',	:to => 'pages#contact'
match '/about',	:to => 'pages#about'
match '/help',	:to => 'pages#help'
match '/videos', :to => 'pages#videos'
match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

root	:to => 'pages#home'
end

app/views/shared/_error_messages.html.erb
<%if !(@user.nil?)%>
<% if @user.errors.any? %>
  <div class="error">
    <h2><%= "#{@user.errors.count} error#{(@user.errors.count > 1) ? "es" : ""}" %> 
        evitaron el registro del usuario: </h2>
    <p>Hubo problemas con los siguientes campos:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<table class="posts" summary="Posts del usuario">
		<%= render :partial => 'shared/feed_item', :collection  => @feed_items %>
	</table>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar">
		<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	</td>
	<td class="post">
		<span class="user">
			<%link_to feed_item.user.name, feed_item.user %>
		</span>
		<span class="content"><%=feed_item.content %></span>
		<span class="timestamp">
			Posteado hace <%= time_ago_in_words(feed_item.created_at) %> por <%= link_to feed_item.user.name, feed_item.user %>.
		</span>
	</td>
	<% if current_user?(feed_item.user) %>
	<td>
		<%= link_to "Borrar", feed_item, :method => :delete,
										:confirm => "Está seguro?",
										:title => feed_item.content,
										:class => "btn danger" %>
	</td>
	<% end %>
</tr>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="input ipost">
		<%= f.text_area :content, :class => "xxlarge" %>
		</div>
	<div class="actions">
		<%= f.submit "Enviar", :class => "btn large primary" %>
	</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> Siguiendo
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "Seguidore") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, :size => 30 %>
	<span class="user_name">
		<%= current_user.name %>
	</span>
	<span class="posts">
		<%= pluralize(current_user.posts.count, "post") %>
	</span>
	</a>
</div>