config/routes.rb
Railsapp::Application.routes.draw do
resources :users do
	member do
		get :following, :followers
	end
end
resources :sessions, :only => [:new, :create, :destroy]
resources :posts, :only => [:create, :destroy]
resources :relationships, :only => [:create, :destroy]
match '/signup',	:to => 'users#new'
match '/signin',	:to => 'sessions#new'
match '/signout',	:to => 'sessions#destroy'
match '/contact',	:to => 'pages#contact'
match '/about',	:to => 'pages#about'
match '/help',	:to => 'pages#help'
match '/videos', :to => 'pages#videos'
match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

root	:to => 'pages#home'
end

app/views/pages/about.html.erb
<h1>Acerca de nosotros</h1>
<p>Elclick.cl - La plataforma del emprendimiento juvenil</p>

app/views/pages/contact.html.erb
<h1>Contacto</h1>
<p>Envíanos un correo a <a href="mailto:contacto@elclick.cl">contacto@elclick.cl</a><br/>
Los leemos todos!</p>

app/views/pages/help.html.erb
<h1>Ayuda</h1>
<p>
	Ayuda: Solo ingresa tu email en el <a href="http://elclick.cl:3003">recuadro</a>!
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
	<table class="front" summary="Sólo usuarios registrados">
	<tr>
		<td class="main">
			<h1 class="post">Que hay de nuevo:</h1>
			   <%=render 'shared/post_form' %>
			   <%= render 'shared/feed' %>
		</td>
		<td class="sidebar round">
			<%= render 'shared/user_info' %>
			<%= render 'shared/stats' %>
		<td>
	</tr>
	</table>
<%else%>
	<h1>Elclick.cl</h1>
<hr>
	<div class="row">
	<div class="span6 columns">
	<h4>
	  Éste es el home de la plataforma de emprendimiento de ElClick.<br/>
	  Para comenzar:<br/>
	</h4>
	</div>
	</div>
	<div class="row">
	<div class="span3 columns offset6">
	<%= link_to "Regístrate!", signup_path, :class => "btn large primary" %>
	</div>
	<div class="span4 columns">
	<div class="alert-message block-message success">
	<p>Usuario <b>registrado</b>?<b> <%= link_to "Ingresa ahora!", signin_path %></b></p>
	</div>
	</div>
	</div>
<% end %>

app/views/pages/videos.html.erb
<h1>Videos inspiradores</h1>
<div class="row">
	<div class="span10 columns">
		<div class="video">
						<object width="526" height="374">
			<param name="movie" value="http://video.ted.com/assets/player/swf/EmbedPlayer.swf"></param>
			<param name="allowFullScreen" value="true" />
			<param name="allowScriptAccess" value="always"/>
			<param name="wmode" value="transparent"></param>
			<param name="bgColor" value="#ffffff"></param>
			<param name="flashvars" value="vu=http://video.ted.com/talk/stream/2009X/Blank/SimonSinek_2009X-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/SimonSinek-2009X.embed_thumbnail.jpg&vw=512&vh=288&ap=0&ti=848&lang=&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=simon_sinek_how_great_leaders_inspire_action;year=2009;theme=not_business_as_usual;theme=unconventional_explanations;theme=a_taste_of_tedx;event=TEDxPuget+Sound+;tag=Business;tag=bullseye;tag=entrepreneur;tag=leadership;tag=sales;tag=selling;tag=success;&preAdTag=tconf.ted/embed;tile=1;sz=512x288;" />
			<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="526" height="374" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2009X/Blank/SimonSinek_2009X-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/SimonSinek-2009X.embed_thumbnail.jpg&vw=512&vh=288&ap=0&ti=848&lang=&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=simon_sinek_how_great_leaders_inspire_action;year=2009;theme=not_business_as_usual;theme=unconventional_explanations;theme=a_taste_of_tedx;event=TEDxPuget+Sound+;tag=Business;tag=bullseye;tag=entrepreneur;tag=leadership;tag=sales;tag=selling;tag=success;&preAdTag=tconf.ted/embed;tile=1;sz=512x288;"></embed>
			</object>
		</div>
	</div>
	<div class="span5 columns">
		<br/>
		<h4>
		Simon Sinek tiene un modelo simple pero poderoso de liderazgo inspirador; todo se basa en un círculo de oro y la pregunta "¿por qué?" Sus ejemplos incluyen a Apple, Martin Luther King y los hermanos Wright. Y como contraparte, TiVo, que (hasta la reciente victoria legal que triplicó el precio de su acción) parecía estar en dificultades.
		</h4>
	</div>
</div>
<div class="row">
	<div class="span5 columns">
		<br/><br/><br/><br/>
		<h4>
		Seth Godin señala que Internet ha acabado con la publicidad masiva y ha resucitado una unidad social del pasado: las tribus. Estas se basan en ideas y valores comunes, las tribus dan el poder a personas ordinarias de liderar y hacer grandes cambios. Él nos invoca a hacer esto.
		</h4>
	</div>
	<div class="span10 columns">
		<div class="video">
			<object width="526" height="374">
				<param name="movie" value="http://video.ted.com/assets/player/swf/EmbedPlayer.swf"></param>
				<param name="allowFullScreen" value="true" />
				<param name="allowScriptAccess" value="always"/>
				<param name="wmode" value="transparent"></param>
				<param name="bgColor" value="#ffffff"></param>
				<param name="flashvars" value="vu=http://video.ted.com/talk/stream/2009/Blank/SethGodin_2009-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/SethGodin-2009.embed_thumbnail.jpg&vw=512&vh=288&ap=0&ti=538&lang=&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=seth_godin_on_the_tribes_we_lead;year=2009;theme=not_business_as_usual;theme=the_rise_of_collaboration;theme=media_that_matters;theme=unconventional_explanations;event=TED2009;tag=book;tag=communication;tag=community;tag=marketing;tag=social+media;tag=society;&preAdTag=tconf.ted/embed;tile=1;sz=512x288;" />
				<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="526" height="374" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2009/Blank/SethGodin_2009-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/SethGodin-2009.embed_thumbnail.jpg&vw=512&vh=288&ap=0&ti=538&lang=&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=seth_godin_on_the_tribes_we_lead;year=2009;theme=not_business_as_usual;theme=the_rise_of_collaboration;theme=media_that_matters;theme=unconventional_explanations;event=TED2009;tag=book;tag=communication;tag=community;tag=marketing;tag=social+media;tag=society;&preAdTag=tconf.ted/embed;tile=1;sz=512x288;"></embed>
			</object>
		</div>
	</div>
</div>
<div class="row">
	<div class="span6 columns offset5">
		<div class="video">
			<h2>
			<a href="http://watch.usnowfilm.com/">Watch: Us Now Film</a>
			</h2>
		</div>
	</div>
</div>
<div class="row">
	<div class="span12 columns">
		<div class="video">
			<iframe width="640" height="390" src="http://www.youtube.com/embed/NugRZGDbPFU?rel=0&amp;hd=1" frameborder="0" allowfullscreen></iframe>
		</div>
	</div>
	<div class="span3 columns">
		<br/><br/><br/><br/>
		<h4>
		One of our most innovative, popular thinkers takes on-in exhilarating style-one of our key questions: Where do good ideas come from?
		</h4>
	</div>
</div>