config/routes.rb
Railsapp::Application.routes.draw do
resources :users do
	member do
		get :following, :followers
	end
end
resources :sessions, :only => [:new, :create, :destroy]
resources :posts, :only => [:create, :destroy]
resources :relationships, :only => [:create, :destroy]
match '/signup',	:to => 'users#new'
match '/signin',	:to => 'sessions#new'
match '/signout',	:to => 'sessions#destroy'
match '/contact',	:to => 'pages#contact'
match '/about',	:to => 'pages#about'
match '/help',	:to => 'pages#help'
match '/videos', :to => 'pages#videos'
match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

root	:to => 'pages#home'
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Acerca de nosotros...", about_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
  <div class="span8 columns offset4">
  <div class="topbar-wrapper" style="z-index: 10000;">
  <div class="topbar">
  <div class="topbar-inner">
  <div class="container">
  <ul class=nav">
  <nav class="round">
      <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Calendario", calendar_path %></li>
	  <li><%= link_to "Videos", videos_path %></li>

	  <% if signed_in? %>
		<li><%= link_to "Usuarios", users_path %></li>
      	<li><%= link_to "Perfil", current_user %></li>
		<li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
      <% end %>
	      <li><%= link_to "Ayuda", help_path %></li>
	  <% if signed_in? %>
	  	<li><%= link_to "Salir...", signout_path, :method => :delete %></li>
	  <% else %>
	  	<li><%= link_to "Ingresa!", signin_path %></li>
      <% end %>
    </ul>
  </nav>
  </div>
  </div>
  </div>
  </div>
  <div class="span4 columns offset8">
  <%= link_to logo, root_path %>
  </div>
</div>
  </div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'bootstrap/bootstrap-1.1.1.css', :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'public/stylesheets/event_calendar.css' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
<%= javascript_include_tag 'event_calendar.js' %>
  <%= csrf_meta_tag %>
  <link rel="shortcut icon" href="/favicon.ico" />
</head>
<body>
<div class="container">
<div class="row">
<div class="span16 columns">
	  <%= render 'layouts/header' %>
      <section class="round">
	  	<% flash.each do |key, value| %>
			<div class="flash <%= key %>"><%= value %> </div>
		<% end %>
        <%= yield %>
      </section>
	  <%= render 'layouts/footer' %>
	</div>
	</div>
	</div>
  </body>
</html>

app/views/layouts/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<script type="text/JavaScript" src="/var/www/elclick/railsapp/public/javascripts/event_calendar.js"></script>
<h1>Calendar</h1>

<%= raw(event_calendar) %>